// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HomeBuddy.Data.Models;

public partial class Booking
{
    public int Id { get; set; }

    public double Price { get; set; }

    public DateTime BookingDay { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public string Note { get; set; }

    public int Status { get; set; }

    public double LongItude { get; set; }

    public double Latitude { get; set; }

    public int HelperId { get; set; }

    public int CartId { get; set; }

    public int UserId { get; set; }

    public DateTime? ServiceDate { get; set; }

    public virtual Cart Cart { get; set; }

    public virtual Helper Helper { get; set; }

    public virtual User User { get; set; }
}