// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HomeBuddy.Data.Models;

public partial class Cart
{
    public int Id { get; set; }

    public DateTime CreateAt { get; set; }

    public double Price { get; set; }

    public int Quantity { get; set; }

    public int UserId { get; set; }

    public int ServiceId { get; set; }

    public virtual Service Service { get; set; }

    public virtual User User { get; set; }
}